// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMU5Jx7TXXziC9HGrNWiKinTcfAgUPp7M',
    appId: '1:311488673256:web:2aefd7c62d08fe2b10a05d',
    messagingSenderId: '311488673256',
    projectId: 'aktivite-gunlugum',
    authDomain: 'aktivite-gunlugum.firebaseapp.com',
    storageBucket: 'aktivite-gunlugum.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZodCzT60MueraWrJpM00iDUv_F-u9Hi4',
    appId: '1:311488673256:android:30e3f65cf447c2ca10a05d',
    messagingSenderId: '311488673256',
    projectId: 'aktivite-gunlugum',
    storageBucket: 'aktivite-gunlugum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDadwAy1kqr2Phyv7W9u0vOjVfTxqIyJGE',
    appId: '1:311488673256:ios:a82dc93f495175e410a05d',
    messagingSenderId: '311488673256',
    projectId: 'aktivite-gunlugum',
    storageBucket: 'aktivite-gunlugum.firebasestorage.app',
    iosClientId: '311488673256-gbf29es27e3rfnpuj2teps5hdgnumeu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sadeceben',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDadwAy1kqr2Phyv7W9u0vOjVfTxqIyJGE',
    appId: '1:311488673256:ios:a82dc93f495175e410a05d',
    messagingSenderId: '311488673256',
    projectId: 'aktivite-gunlugum',
    storageBucket: 'aktivite-gunlugum.firebasestorage.app',
    iosClientId: '311488673256-gbf29es27e3rfnpuj2teps5hdgnumeu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sadeceben',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMU5Jx7TXXziC9HGrNWiKinTcfAgUPp7M',
    appId: '1:311488673256:web:fe3ba3dcd9e7701b10a05d',
    messagingSenderId: '311488673256',
    projectId: 'aktivite-gunlugum',
    authDomain: 'aktivite-gunlugum.firebaseapp.com',
    storageBucket: 'aktivite-gunlugum.firebasestorage.app',
  );

}